export default {
    DATA_IMPORT:"DATA_IMPORT",
    ADD_CONTACT:"ADD_CONTACT",
    DELETE_CONTACTS:'DELTE_CONTACTS',
    EDIT_CONTACT:'EDIT_CONTACT',
    LOGIN_CONTACT:'LOGIN_CONTACT',
    SENT_MESSAGE:'SENT_MESSAGE',
    GET_MESSAGES:'GET_MESSAGES',
}